[tool.poetry]
name = "pytools"
version = "0.1.0"
description = ""
authors = ["Luscarvalho <luscarvalhox@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytube = "^12.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
